<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows10.0.17763</TargetFramework>
        <Nullable>annotations</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <UseWindowsForms>true</UseWindowsForms>
        <!-- <ApplicationIcon>Assets\voicelink.ico</ApplicationIcon> -->
        <Title>Flex Phone</Title>
        <Company>Devine Creations</Company>
        <Product>Flex Phone</Product>
        <Description>Native Windows Flex Phone client for Flex PBX calling</Description>
        <Copyright>Copyright 2024-2025 Devine Creations</Copyright>
        <Version>1.0.6</Version>
        <AssemblyVersion>1.0.6.0</AssemblyVersion>
        <FileVersion>1.0.6.94</FileVersion>
        <InformationalVersion>1.0.6+94</InformationalVersion>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
        <PackageReference Include="SocketIOClient" Version="3.1.1" />
        <PackageReference Include="SIPSorcery" Version="10.0.6" />
        <PackageReference Include="SIPSorceryMedia.Windows" Version="8.0.14" />
        <PackageReference Include="NAudio" Version="2.2.1" />
        <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
    </ItemGroup>
    <ItemGroup>
        <None Remove="Assets\**" />
        <Resource Include="Assets\**" />
        <Content Include="Native\nvdaControllerClient64.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </Content>
    </ItemGroup>
</Project>
